import { CodeTemplate } from "@/lib/types";

export const dualUltrasonicObstacleAvoidance: CodeTemplate = {
  id: "dual-ultrasonic__obstacle-avoidance",
  sensorId: "dual-ultrasonic",
  behaviorId: "obstacle-avoidance",
  explanation:
    "This works just like the single-sensor Obstacle Avoidance template, except it pings two ultrasonic sensors every loop instead of one - a high one and a low one, both facing forward. Mounting them at different heights means the robot catches obstacles a single sensor at one height would miss entirely: something small sitting on the floor might pass right under a sensor mounted high up, and something like a tabletop edge might pass right over a sensor mounted low down. Since both sensors point straight ahead rather than off to a side, there's no left/right information to use - so exactly like the single-sensor version, if either sensor sees something closer than the stop distance, the robot stops, backs off briefly, and turns the same fixed direction before driving forward again. The two sensors are pinged one at a time with a brief pause in between, so the second sensor's echo doesn't get confused by the first sensor's pulse still bouncing around. Driving and turning both use the same ramped-speed motor control as the other Robot Car projects - the robot steps its speed up gradually instead of jumping straight to full power, so both motors don't demand their biggest current draw at the same instant and leave one side stalled.",
  parameters: [
    {
      id: "motorSpeed",
      label: "Motor Speed",
      type: "number",
      defaultValue: 150,
      min: 0,
      max: 255,
      step: 5,
      unit: "PWM (0-255)",
    },
    {
      id: "stopDistance",
      label: "Stop Distance",
      type: "number",
      defaultValue: 15,
      min: 5,
      max: 100,
      step: 1,
      unit: "cm",
    },
  ],
  code: `/*
  Obstacle Avoidance with Two Ultrasonic Sensors (2x HC-SR04)
  Generated by the Robot Code Builder
*/

// Both sensors face forward - one mounted higher, one mounted lower - so
// together they cover obstacles a single sensor's beam would miss.
const int highTrigPin = 2;
const int highEchoPin = 3;
const int lowTrigPin = 4;
const int lowEchoPin = 6;

// The robot has 4 motors, but both motors on the same side always move
// together, so they're wired in parallel to the same L298N output and
// controlled as one unit here. IN1/IN2 (and IN3/IN4) pick the direction
// for that side; ENA (and ENB) is the PWM pin that sets its speed.
const int leftEnablePin = 5;    // ENA
const int leftForwardPin = 7;   // IN1
const int leftBackwardPin = 8;  // IN2
const int rightEnablePin = 11;  // ENB
const int rightForwardPin = 12; // IN3
const int rightBackwardPin = 13; // IN4

const int motorSpeed = {{motorSpeed}};   // 0-255
const int stopDistance = {{stopDistance}}; // centimeters

// Jumping straight to full speed makes both motors demand their biggest
// current draw (to overcome standing friction) in the same instant, which
// can sag the power supply enough that one side never gets moving. Ramping
// speed up a step at a time - the same trick the Motor Sweep Test uses -
// spreads that demand out instead.
const int rampStepDelayMs = 15;

int leftSpeed = 0;
int rightSpeed = 0;

void setup() {
  pinMode(highTrigPin, OUTPUT);
  pinMode(highEchoPin, INPUT);
  pinMode(lowTrigPin, OUTPUT);
  pinMode(lowEchoPin, INPUT);

  pinMode(leftEnablePin, OUTPUT);
  pinMode(leftForwardPin, OUTPUT);
  pinMode(leftBackwardPin, OUTPUT);
  pinMode(rightEnablePin, OUTPUT);
  pinMode(rightForwardPin, OUTPUT);
  pinMode(rightBackwardPin, OUTPUT);
}

long readDistanceCm(int trigPin, int echoPin) {
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);

  long duration = pulseIn(echoPin, HIGH);
  return duration / 29 / 2;
}

// Moves both motors' PWM speed toward their targets a step at a time,
// instead of jumping there in one instant.
void rampTo(int leftTarget, int rightTarget) {
  while (leftSpeed != leftTarget || rightSpeed != rightTarget) {
    if (leftSpeed < leftTarget) {
      leftSpeed = min(leftSpeed + 5, leftTarget);
    } else if (leftSpeed > leftTarget) {
      leftSpeed = max(leftSpeed - 5, leftTarget);
    }

    if (rightSpeed < rightTarget) {
      rightSpeed = min(rightSpeed + 5, rightTarget);
    } else if (rightSpeed > rightTarget) {
      rightSpeed = max(rightSpeed - 5, rightTarget);
    }

    analogWrite(leftEnablePin, leftSpeed);
    analogWrite(rightEnablePin, rightSpeed);
    delay(rampStepDelayMs);
  }
}

void driveForward() {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, HIGH);
  digitalWrite(rightBackwardPin, LOW);
  rampTo(motorSpeed, motorSpeed);
}

// Cuts both motors immediately (no ramp-down needed - only starting from a
// stop draws enough current to cause trouble) and leaves the direction pins
// LOW so the next move starts from a clean, fully-stopped state.
void stopMotors() {
  analogWrite(leftEnablePin, 0);
  analogWrite(rightEnablePin, 0);
  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, LOW);
  leftSpeed = 0;
  rightSpeed = 0;
}

void turnAway() {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, HIGH);
  rampTo(motorSpeed, motorSpeed);
  delay(400);
  stopMotors();
}

void loop() {
  long highDistance = readDistanceCm(highTrigPin, highEchoPin);
  delay(10); // brief pause so the low sensor's echo isn't confused by the high sensor's pulse
  long lowDistance = readDistanceCm(lowTrigPin, lowEchoPin);

  bool highBlocked = highDistance > 0 && highDistance < stopDistance;
  bool lowBlocked = lowDistance > 0 && lowDistance < stopDistance;

  if (highBlocked || lowBlocked) {
    stopMotors();
    delay(200);
    turnAway();
  } else {
    driveForward();
  }
}
`,
};
