import { CodeTemplate } from "@/lib/types";

export const irLineSensorsLineFollowing: CodeTemplate = {
  id: "ir-line-sensors__line-following",
  sensorId: "ir-line-sensors",
  behaviorId: "line-following",
  explanation:
    "Each IR sensor module shines infrared light down at the floor and measures how much bounces back - a light-colored floor reflects a lot, so the sensor's output stays HIGH, while a black line absorbs most of the light, so the output drops LOW when the sensor is right over it. The two sensors are mounted side by side, straddling where the line should run underneath the robot. If both sensors see the line, it's centered, so the robot just drives straight. If only the left sensor sees it, the robot has drifted too far right, so the code slows the left wheel to curve the robot back toward the line; if only the right sensor sees it, the same thing happens in reverse. If neither sensor sees the line, the robot stops rather than guessing which way to search for it. Unlike the other Robot Car projects, this one sets each wheel's speed directly instead of ramping it up gradually - line following has to react within a single loop, many times a second, and a gradual ramp would lag behind the line and let the robot swerve off before it caught up. That ramp exists specifically to stop both motors from demanding their full starting current at the same instant; here only one side's speed ever changes at a time, so that risk doesn't apply the same way.",
  parameters: [
    {
      id: "motorSpeed",
      label: "Motor Speed",
      type: "number",
      defaultValue: 150,
      min: 0,
      max: 255,
      step: 5,
      unit: "PWM (0-255)",
    },
  ],
  code: `/*
  Line Following with Two IR Sensors (2x TCRT5000)
  Generated by the Robot Code Builder
*/

const int leftLineSensorPin = 2;
const int rightLineSensorPin = 3;

// The robot has 4 motors, but both motors on the same side always move
// together, so they're wired in parallel to the same L298N output and
// controlled as one unit here. IN1/IN2 (and IN3/IN4) pick the direction
// for that side; ENA (and ENB) is the PWM pin that sets its speed.
const int leftEnablePin = 5;    // ENA
const int leftForwardPin = 7;   // IN1
const int leftBackwardPin = 8;  // IN2
const int rightEnablePin = 11;  // ENB
const int rightForwardPin = 12; // IN3
const int rightBackwardPin = 13; // IN4

const int motorSpeed = {{motorSpeed}}; // 0-255

void setup() {
  pinMode(leftLineSensorPin, INPUT);
  pinMode(rightLineSensorPin, INPUT);

  pinMode(leftEnablePin, OUTPUT);
  pinMode(leftForwardPin, OUTPUT);
  pinMode(leftBackwardPin, OUTPUT);
  pinMode(rightEnablePin, OUTPUT);
  pinMode(rightForwardPin, OUTPUT);
  pinMode(rightBackwardPin, OUTPUT);
}

// Sets each side's speed directly instead of ramping up gradually like the
// other Robot Car projects do. Line following needs to react within a
// single loop, many times a second, so a gradual ramp would lag behind the
// line and make the robot swerve off it. That ramp exists to keep both
// motors from demanding their full starting current at the same instant -
// here only one side's speed ever changes at a time, so that risk doesn't
// apply the same way.
void driveMotors(int leftSpeed, int rightSpeed) {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, HIGH);
  digitalWrite(rightBackwardPin, LOW);
  analogWrite(leftEnablePin, leftSpeed);
  analogWrite(rightEnablePin, rightSpeed);
}

void stopMotors() {
  analogWrite(leftEnablePin, 0);
  analogWrite(rightEnablePin, 0);
  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, LOW);
}

void loop() {
  // Most of these sensor modules pull their output LOW over a black line
  // (less infrared reflects back) and HIGH over a lighter floor. If your
  // sensors read backwards from this, swap == LOW for == HIGH below.
  bool leftOnLine = digitalRead(leftLineSensorPin) == LOW;
  bool rightOnLine = digitalRead(rightLineSensorPin) == LOW;

  if (leftOnLine && rightOnLine) {
    // Line under both sensors - drive straight.
    driveMotors(motorSpeed, motorSpeed);
  } else if (leftOnLine && !rightOnLine) {
    // Line has drifted under the left sensor, so the robot is too far
    // right - slow the left wheel so it curves back left.
    driveMotors(0, motorSpeed);
  } else if (!leftOnLine && rightOnLine) {
    // Line has drifted under the right sensor - slow the right wheel so
    // it curves back right.
    driveMotors(motorSpeed, 0);
  } else {
    // Neither sensor sees the line - stop rather than guess which way to go.
    stopMotors();
  }
}
`,
};
