import { CodeTemplate } from "@/lib/types";

export const irRemoteRemoteControl: CodeTemplate = {
  id: "ir-remote__remote-control",
  sensorId: "ir-remote",
  behaviorId: "remote-control",
  explanation:
    "Every time you press a button on the remote, it blinks out a short pattern of infrared light. The receiver on the robot picks that pattern up and turns it back into a code number. The code checks that number against the five buttons it knows (forward, backward, left, right, stop) and drives the motors accordingly. The ENA and ENB speed pins on the L298N are assumed to have their jumpers left in, so the motors always run at full speed - the code only ever needs to turn each side on or off and pick its direction, which is why it only uses digitalWrite() on the motor pins. Every code the receiver picks up also gets printed to the Serial Monitor, so you can open it (Tools > Serial Monitor, 9600 baud), press each button on your remote, and write down which code goes with which button - then swap those codes into CODE_FORWARD, CODE_BACKWARD, etc. below. If you let go of the button, the robot keeps doing whatever it was just doing for a few seconds before stopping on its own, in case the remote loses the signal for a moment.",
  parameters: [
    {
      id: "irReceiverPin",
      label: "IR Receiver Pin",
      type: "number",
      defaultValue: 11,
      min: 2,
      max: 13,
      step: 1,
      unit: "digital pin",
    },
    {
      id: "commandTimeoutMs",
      label: "Keep Doing Last Command For",
      type: "number",
      defaultValue: 5000,
      min: 500,
      max: 10000,
      step: 250,
      unit: "ms",
    },
  ],
  code: `/*
  Remote Control with an IR Receiver (HX1838)
  Generated by the Robot Code Builder

  This sketch needs the "IRremote" library (by Armin Joachimsmeyer).
  Install it from Sketch > Include Library > Manage Libraries in the
  Arduino IDE, then search for "IRremote".
*/

#include <IRremote.hpp>

const int irReceiverPin = {{irReceiverPin}};
const unsigned long commandTimeoutMs = {{commandTimeoutMs}};

// These are the standard button codes for the small 21-button remote that
// ships with most Arduino robot-car kits (the ones with an HX1838 receiver).
// If your remote is different, run the IRremote library's "ReceiveDemo"
// example, press each button, and swap in the codes it prints.
const unsigned long CODE_FORWARD = 0xFF18E7;
const unsigned long CODE_BACKWARD = 0xFF4AB5;
const unsigned long CODE_LEFT = 0xFF10EF;
const unsigned long CODE_RIGHT = 0xFF5AA5;
const unsigned long CODE_STOP = 0xFF38C7;

// This is the code sent while a button is being held down, instead of
// resending the button's own code over and over.
const unsigned long CODE_REPEAT = 0xFFFFFFFF;

// The ENA/ENB speed pins are assumed to be jumpered to always-on, so only
// the direction pins (IN1-IN4) are controlled here.
const int leftForwardPin = 5;   // IN1
const int leftBackwardPin = 6;  // IN2
const int rightForwardPin = 7;  // IN3
const int rightBackwardPin = 8; // IN4

unsigned long lastCommand = CODE_STOP;
unsigned long lastSignalTime = 0;

void setup() {
  Serial.begin(9600);
  IrReceiver.begin(irReceiverPin);

  pinMode(leftForwardPin, OUTPUT);
  pinMode(leftBackwardPin, OUTPUT);
  pinMode(rightForwardPin, OUTPUT);
  pinMode(rightBackwardPin, OUTPUT);
}

void driveForward() {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, HIGH);
  digitalWrite(rightBackwardPin, LOW);
}

void driveBackward() {
  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, HIGH);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, HIGH);
}

void turnLeft() {
  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, HIGH);
  digitalWrite(rightForwardPin, HIGH);
  digitalWrite(rightBackwardPin, LOW);
}

void turnRight() {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, HIGH);
}

void stopMotors() {
  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, LOW);
}

void loop() {
  if (IrReceiver.decode()) {
    unsigned long code = IrReceiver.decodedIRData.decodedRawData;

    // Print every code the receiver picks up. Open the Serial Monitor,
    // press a button on your remote, and see what shows up here - that's
    // the code to use for that button below.
    Serial.print("IR code received: 0x");
    Serial.println(code, HEX);

    // A repeat code means the last real button is still being held down,
    // so keep doing whatever lastCommand already says.
    if (code != CODE_REPEAT) {
      lastCommand = code;
    }
    lastSignalTime = millis();

    IrReceiver.resume();
  }

  // Once you let go of a button, no more codes come in. Rather than
  // stopping right away, keep doing the last command for a while in case
  // it was just a brief gap in the signal - only stop once commandTimeoutMs
  // has passed with nothing new received.
  if (millis() - lastSignalTime > commandTimeoutMs) {
    lastCommand = CODE_STOP;
  }

  if (lastCommand == CODE_FORWARD) {
    driveForward();
  } else if (lastCommand == CODE_BACKWARD) {
    driveBackward();
  } else if (lastCommand == CODE_LEFT) {
    turnLeft();
  } else if (lastCommand == CODE_RIGHT) {
    turnRight();
  } else {
    stopMotors();
  }
}
`,
};
