import { CodeTemplate } from "@/lib/types";

export const soundSensorSoundControl: CodeTemplate = {
  id: "sound-sensor__sound-control",
  sensorId: "sound-sensor",
  behaviorId: "sound-control",
  explanation:
    "The sound sensor's microphone rests at a middle voltage (about half of 0-1023, or 512) when it's quiet, and swings above and below that resting level as sound waves hit it. Every loop, the code listens for a short 50-millisecond window and measures two things about what it heard: loudness is how big that swing got (the biggest reading minus the smallest), and pitch is estimated by counting how many times the signal crossed back over the resting level in that same window - a higher-pitched sound crosses back and forth faster, the same reason a guitar's thin high string vibrates faster than its thick low string. If the sound wasn't loud enough, the robot stops. If it was loud and high-pitched (like a whistle), the robot spins in place. If it was loud but not high-pitched (like a clap or a shout), the robot drives forward. Driving and spinning both use the same ramped-speed motor control as the other Robot Car projects - the robot steps its speed up gradually instead of jumping straight to full power, so both motors don't demand their biggest current draw at the same instant and leave one side stalled.",
  parameters: [
    {
      id: "motorSpeed",
      label: "Motor Speed",
      type: "number",
      defaultValue: 150,
      min: 0,
      max: 255,
      step: 5,
      unit: "PWM (0-255)",
    },
    {
      id: "loudnessThreshold",
      label: "Loudness Threshold",
      type: "number",
      defaultValue: 100,
      min: 10,
      max: 500,
      step: 10,
      unit: "analog swing (0-1023)",
    },
    {
      id: "pitchThresholdHz",
      label: "High-Pitch Threshold",
      type: "number",
      defaultValue: 1000,
      min: 200,
      max: 4000,
      step: 100,
      unit: "Hz",
    },
  ],
  code: `/*
  Sound Control with a Sound Sensor Module (KY-038)
  Generated by the Robot Code Builder
*/

const int soundPin = A0;

// The robot has 4 motors, but both motors on the same side always move
// together, so they're wired in parallel to the same L298N output and
// controlled as one unit here. IN1/IN2 (and IN3/IN4) pick the direction
// for that side; ENA (and ENB) is the PWM pin that sets its speed.
const int leftEnablePin = 5;    // ENA
const int leftForwardPin = 7;   // IN1
const int leftBackwardPin = 8;  // IN2
const int rightEnablePin = 11;  // ENB
const int rightForwardPin = 12; // IN3
const int rightBackwardPin = 13; // IN4

const int motorSpeed = {{motorSpeed}};               // 0-255
const int loudnessThreshold = {{loudnessThreshold}}; // analog swing needed to count as "loud"
const int pitchThresholdHz = {{pitchThresholdHz}};   // frequency needed to count as "high-pitched"

const unsigned long sampleWindowMs = 50; // how long to listen before deciding what it heard
const int quietMidpoint = 512;           // resting analog value with no sound (half of 0-1023)

// Jumping straight to full speed makes both motors demand their biggest
// current draw (to overcome standing friction) in the same instant, which
// can sag the power supply enough that one side never gets moving. Ramping
// speed up a step at a time - the same trick the Motor Sweep Test uses -
// spreads that demand out instead.
const int rampStepDelayMs = 15;

int leftSpeed = 0;
int rightSpeed = 0;

int lastLoudness = 0;
int lastFrequencyHz = 0;

void setup() {
  pinMode(leftEnablePin, OUTPUT);
  pinMode(leftForwardPin, OUTPUT);
  pinMode(leftBackwardPin, OUTPUT);
  pinMode(rightEnablePin, OUTPUT);
  pinMode(rightForwardPin, OUTPUT);
  pinMode(rightBackwardPin, OUTPUT);
  // soundPin is an analog input pin - no pinMode() call needed for it.
}

// Listens to the microphone for sampleWindowMs and figures out how loud the
// sound was (the biggest swing away from the resting level) and roughly how
// high-pitched it was (how many times the signal crossed back over the
// resting level - more crossings in the same window means a higher pitch).
void listenToSound() {
  unsigned long startTime = millis();
  int sampleMin = 1023;
  int sampleMax = 0;
  int crossings = 0;
  bool wasAboveMidpoint = false;
  bool firstSample = true;

  while (millis() - startTime < sampleWindowMs) {
    int sample = analogRead(soundPin);
    if (sample < sampleMin) sampleMin = sample;
    if (sample > sampleMax) sampleMax = sample;

    bool isAboveMidpoint = sample > quietMidpoint;
    if (!firstSample && isAboveMidpoint && !wasAboveMidpoint) {
      crossings++;
    }
    wasAboveMidpoint = isAboveMidpoint;
    firstSample = false;
  }

  lastLoudness = sampleMax - sampleMin;
  lastFrequencyHz = crossings * (1000 / sampleWindowMs);
}

// Moves both motors' PWM speed toward their targets a step at a time,
// instead of jumping there in one instant.
void rampTo(int leftTarget, int rightTarget) {
  while (leftSpeed != leftTarget || rightSpeed != rightTarget) {
    if (leftSpeed < leftTarget) {
      leftSpeed = min(leftSpeed + 5, leftTarget);
    } else if (leftSpeed > leftTarget) {
      leftSpeed = max(leftSpeed - 5, leftTarget);
    }

    if (rightSpeed < rightTarget) {
      rightSpeed = min(rightSpeed + 5, rightTarget);
    } else if (rightSpeed > rightTarget) {
      rightSpeed = max(rightSpeed - 5, rightTarget);
    }

    analogWrite(leftEnablePin, leftSpeed);
    analogWrite(rightEnablePin, rightSpeed);
    delay(rampStepDelayMs);
  }
}

void driveForward() {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, HIGH);
  digitalWrite(rightBackwardPin, LOW);
  rampTo(motorSpeed, motorSpeed);
}

void spinInPlace() {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, HIGH);
  rampTo(motorSpeed, motorSpeed);
}

// Cuts both motors immediately (no ramp-down needed - only starting from a
// stop draws enough current to cause trouble) and leaves the direction pins
// LOW so the next move starts from a clean, fully-stopped state.
void stopMotors() {
  analogWrite(leftEnablePin, 0);
  analogWrite(rightEnablePin, 0);
  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, LOW);
  leftSpeed = 0;
  rightSpeed = 0;
}

void loop() {
  listenToSound();

  if (lastLoudness < loudnessThreshold) {
    stopMotors();
  } else if (lastFrequencyHz > pitchThresholdHz) {
    spinInPlace();
  } else {
    driveForward();
  }
}
`,
};
