import { CodeTemplate } from "@/lib/types";

export const tripleUltrasonicObstacleAvoidance: CodeTemplate = {
  id: "triple-ultrasonic__obstacle-avoidance",
  sensorId: "triple-ultrasonic",
  behaviorId: "obstacle-avoidance",
  explanation:
    "This combines the ideas behind the vertical and horizontal dual-sensor templates into one. The middle sensor is mounted higher and points straight ahead, so - like the vertical template - it catches obstacles the two lower side sensors might miss, but it has no left/right information of its own. The left and right sensors are mounted lower and angled toward their own side, so - like the horizontal template - each one knows which side of the robot an obstacle is actually on. Because of that, the side sensors get priority for deciding which way to turn: if only the left sensor sees something, the robot turns right; if only the right sensor does, it turns left; if both do at once, it turns away from whichever is closer. If only the middle sensor sees something - nothing directly to either side - there's no side information to use, so the robot falls back to turning a fixed direction, the same way the single-sensor and vertical dual-sensor templates do. All three sensors are pinged one at a time with a brief pause in between so their echoes don't get confused with each other. Driving and turning both use the same ramped-speed motor control as the other Robot Car projects - the robot steps its speed up gradually instead of jumping straight to full power, so both motors don't demand their biggest current draw at the same instant and leave one side stalled.",
  parameters: [
    {
      id: "motorSpeed",
      label: "Motor Speed",
      type: "number",
      defaultValue: 150,
      min: 0,
      max: 255,
      step: 5,
      unit: "PWM (0-255)",
    },
    {
      id: "stopDistance",
      label: "Stop Distance",
      type: "number",
      defaultValue: 15,
      min: 5,
      max: 100,
      step: 1,
      unit: "cm",
    },
  ],
  code: `/*
  Obstacle Avoidance with Three Ultrasonic Sensors (3x HC-SR04)
  Generated by the Robot Code Builder
*/

// The middle sensor is mounted higher and points straight forward; the left
// and right sensors are mounted lower, each angled toward its own side.
const int middleTrigPin = 9;
const int middleEchoPin = 10;
const int leftTrigPin = 2;
const int leftEchoPin = 3;
const int rightTrigPin = 4;
const int rightEchoPin = 6;

// The robot has 4 motors, but both motors on the same side always move
// together, so they're wired in parallel to the same L298N output and
// controlled as one unit here. IN1/IN2 (and IN3/IN4) pick the direction
// for that side; ENA (and ENB) is the PWM pin that sets its speed.
const int leftEnablePin = 5;    // ENA
const int leftForwardPin = 7;   // IN1
const int leftBackwardPin = 8;  // IN2
const int rightEnablePin = 11;  // ENB
const int rightForwardPin = 12; // IN3
const int rightBackwardPin = 13; // IN4

const int motorSpeed = {{motorSpeed}};   // 0-255
const int stopDistance = {{stopDistance}}; // centimeters

// Jumping straight to full speed makes both motors demand their biggest
// current draw (to overcome standing friction) in the same instant, which
// can sag the power supply enough that one side never gets moving. Ramping
// speed up a step at a time - the same trick the Motor Sweep Test uses -
// spreads that demand out instead.
const int rampStepDelayMs = 15;

int leftSpeed = 0;
int rightSpeed = 0;

void setup() {
  pinMode(middleTrigPin, OUTPUT);
  pinMode(middleEchoPin, INPUT);
  pinMode(leftTrigPin, OUTPUT);
  pinMode(leftEchoPin, INPUT);
  pinMode(rightTrigPin, OUTPUT);
  pinMode(rightEchoPin, INPUT);

  pinMode(leftEnablePin, OUTPUT);
  pinMode(leftForwardPin, OUTPUT);
  pinMode(leftBackwardPin, OUTPUT);
  pinMode(rightEnablePin, OUTPUT);
  pinMode(rightForwardPin, OUTPUT);
  pinMode(rightBackwardPin, OUTPUT);
}

long readDistanceCm(int trigPin, int echoPin) {
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);

  long duration = pulseIn(echoPin, HIGH);
  return duration / 29 / 2;
}

// Moves both motors' PWM speed toward their targets a step at a time,
// instead of jumping there in one instant.
void rampTo(int leftTarget, int rightTarget) {
  while (leftSpeed != leftTarget || rightSpeed != rightTarget) {
    if (leftSpeed < leftTarget) {
      leftSpeed = min(leftSpeed + 5, leftTarget);
    } else if (leftSpeed > leftTarget) {
      leftSpeed = max(leftSpeed - 5, leftTarget);
    }

    if (rightSpeed < rightTarget) {
      rightSpeed = min(rightSpeed + 5, rightTarget);
    } else if (rightSpeed > rightTarget) {
      rightSpeed = max(rightSpeed - 5, rightTarget);
    }

    analogWrite(leftEnablePin, leftSpeed);
    analogWrite(rightEnablePin, rightSpeed);
    delay(rampStepDelayMs);
  }
}

void driveForward() {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, HIGH);
  digitalWrite(rightBackwardPin, LOW);
  rampTo(motorSpeed, motorSpeed);
}

// Cuts both motors immediately (no ramp-down needed - only starting from a
// stop draws enough current to cause trouble) and leaves the direction pins
// LOW so the next move starts from a clean, fully-stopped state.
void stopMotors() {
  analogWrite(leftEnablePin, 0);
  analogWrite(rightEnablePin, 0);
  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, LOW);
  leftSpeed = 0;
  rightSpeed = 0;
}

// Pivots right in place (left side forward, right side backward) - turns
// away from something the left sensor saw, or a default direction when
// only the middle sensor saw something.
void turnRight() {
  digitalWrite(leftForwardPin, HIGH);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, HIGH);
  rampTo(motorSpeed, motorSpeed);
  delay(400);
  stopMotors();
}

// Pivots left in place (left side backward, right side forward) - turns
// away from something the right sensor saw.
void turnLeft() {
  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, HIGH);
  digitalWrite(rightForwardPin, HIGH);
  digitalWrite(rightBackwardPin, LOW);
  rampTo(motorSpeed, motorSpeed);
  delay(400);
  stopMotors();
}

void loop() {
  long middleDistance = readDistanceCm(middleTrigPin, middleEchoPin);
  delay(10); // brief pause so the next sensor's echo isn't confused by this one's pulse
  long leftDistance = readDistanceCm(leftTrigPin, leftEchoPin);
  delay(10);
  long rightDistance = readDistanceCm(rightTrigPin, rightEchoPin);

  bool middleBlocked = middleDistance > 0 && middleDistance < stopDistance;
  bool leftBlocked = leftDistance > 0 && leftDistance < stopDistance;
  bool rightBlocked = rightDistance > 0 && rightDistance < stopDistance;

  if (middleBlocked || leftBlocked || rightBlocked) {
    stopMotors();
    delay(200);

    if (leftBlocked && rightBlocked) {
      // Something on both sides - turn away from whichever is closer.
      if (leftDistance <= rightDistance) {
        turnRight();
      } else {
        turnLeft();
      }
    } else if (leftBlocked) {
      turnRight();
    } else if (rightBlocked) {
      turnLeft();
    } else {
      // Only the middle sensor saw something - it has no left/right
      // information, so just turn a fixed direction.
      turnRight();
    }
  } else {
    driveForward();
  }
}
`,
};
