import { GeneralProject } from "@/lib/types";

export const ledBlink: GeneralProject = {
  id: "led-blink",
  name: "Blink an LED",
  description:
    "Turn an LED on and off over and over. The classic first Arduino program.",
  wiringImage: "/images/wiring/led-blink.svg",
  pins: [
    { label: "LED long leg (+)", arduinoPin: "13, through a resistor" },
    { label: "LED short leg (-)", arduinoPin: "GND" },
  ],
  parameters: [
    {
      id: "ledPin",
      label: "LED Pin",
      type: "number",
      defaultValue: 13,
      min: 2,
      max: 13,
      step: 1,
      unit: "digital pin",
    },
    {
      id: "blinkDelayMs",
      label: "Blink Delay",
      type: "number",
      defaultValue: 500,
      min: 50,
      max: 5000,
      step: 50,
      unit: "ms",
    },
  ],
  explanation:
    "An LED only has two states: on or off. digitalWrite() sets a pin HIGH (about 5 volts, which lights the LED) or LOW (0 volts, which turns it off). The delay() calls just pause the program for a moment so the LED stays in each state long enough for you to see it, instead of switching faster than your eye can follow. Always wire the LED through a resistor (220-330 ohm is typical) - without one, the LED draws too much current and can burn out.",
  code: `/*
  Blink an LED
  Generated by the Robot Code Builder
*/

const int ledPin = {{ledPin}};
const int blinkDelayMs = {{blinkDelayMs}};

void setup() {
  pinMode(ledPin, OUTPUT);
}

void loop() {
  digitalWrite(ledPin, HIGH);
  delay(blinkDelayMs);
  digitalWrite(ledPin, LOW);
  delay(blinkDelayMs);
}
`,
};
