import { GeneralProject } from "@/lib/types";

export const motorSweepTest: GeneralProject = {
  id: "motor-sweep-test",
  name: "Motor Sweep Test",
  description:
    "Ramps each drive motor up and down, one at a time, in both directions, then ramps both together to check the robot drives straight. Run this first on a freshly wired robot to confirm both motors are wired correctly and spin the way you expect before trying any Robot Car project.",
  wiringImage: "/images/wiring/motor-sweep-test.svg",
  pins: [
    { label: "ENA (left speed)", arduinoPin: "5" },
    { label: "IN1 (left direction)", arduinoPin: "7" },
    { label: "IN2 (left direction)", arduinoPin: "8" },
    { label: "ENB (right speed)", arduinoPin: "11" },
    { label: "IN3 (right direction)", arduinoPin: "12" },
    { label: "IN4 (right direction)", arduinoPin: "13" },
    { label: "L298N GND", arduinoPin: "GND" },
  ],
  parameters: [
    {
      id: "maxSpeed",
      label: "Top Speed to Ramp To",
      type: "number",
      defaultValue: 200,
      min: 50,
      max: 255,
      step: 5,
      unit: "PWM (0-255)",
    },
    {
      id: "stepDelayMs",
      label: "Delay Between Speed Steps",
      type: "number",
      defaultValue: 20,
      min: 5,
      max: 100,
      step: 5,
      unit: "ms",
    },
    {
      id: "pauseBetweenTestsMs",
      label: "Pause Between Each Test",
      type: "number",
      defaultValue: 500,
      min: 0,
      max: 3000,
      step: 100,
      unit: "ms",
    },
  ],
  explanation:
    "This project is a diagnostic, not a robot behavior - its only job is to prove the wiring is right before you build anything on top of it. Unlike the Robot Car projects, it assumes the ENA and ENB jumpers have been removed from the L298N, so each side's speed pin has to be driven with analogWrite() instead of always running at full power the way a jumpered pin would. The IN1/IN2 (and IN3/IN4) pins still just pick a direction with digitalWrite(), exactly like the Robot Car projects - the difference here is only in how speed is controlled. The code first ramps one motor's speed from 0 up to your chosen top speed and back down to 0, forward then backward, then does the same for the other motor - printing to the Serial Monitor as it goes so you can match what you see on screen to what you see the wheel do. If a wheel spins the wrong way, swap that motor's two wires at the L298N output screw terminals and try again - don't change the code to fix a backwards wheel. Once both motors have been checked individually, it ramps them together, forward then backward, which is the best way to catch a robot that pulls to one side even though each wheel tested fine on its own.",
  code: `/*
  Motor Sweep Test
  Generated by the Robot Code Builder

  Run this before any Robot Car project to confirm both motors are wired
  correctly. It assumes the ENA and ENB jumpers have been removed from the
  L298N, so speed is set here with analogWrite() instead of the motors
  always running at full power.
*/

const int leftEnablePin = 5;    // ENA
const int leftForwardPin = 7;   // IN1
const int leftBackwardPin = 8;  // IN2
const int rightEnablePin = 11;  // ENB
const int rightForwardPin = 12; // IN3
const int rightBackwardPin = 13; // IN4

const int maxSpeed = {{maxSpeed}};                     // 0-255
const int stepDelayMs = {{stepDelayMs}};                 // milliseconds between each speed step
const int pauseBetweenTestsMs = {{pauseBetweenTestsMs}}; // milliseconds to rest between each test

void setup() {
  Serial.begin(9600);

  pinMode(leftEnablePin, OUTPUT);
  pinMode(leftForwardPin, OUTPUT);
  pinMode(leftBackwardPin, OUTPUT);
  pinMode(rightEnablePin, OUTPUT);
  pinMode(rightForwardPin, OUTPUT);
  pinMode(rightBackwardPin, OUTPUT);
}

// Ramps one motor's speed from 0 up to maxSpeed and back down to 0 in a
// single direction, printing along the way so you can watch the Serial
// Monitor while you watch the wheel.
void sweepMotor(const char* motorName, int enablePin, int forwardPin, int backwardPin, bool forward) {
  digitalWrite(forwardPin, forward ? HIGH : LOW);
  digitalWrite(backwardPin, forward ? LOW : HIGH);

  Serial.print(motorName);
  Serial.println(forward ? ": forward, ramping up" : ": backward, ramping up");
  for (int speed = 0; speed <= maxSpeed; speed += 5) {
    analogWrite(enablePin, speed);
    delay(stepDelayMs);
  }

  Serial.println("...ramping back down");
  for (int speed = maxSpeed; speed >= 0; speed -= 5) {
    analogWrite(enablePin, speed);
    delay(stepDelayMs);
  }

  digitalWrite(forwardPin, LOW);
  digitalWrite(backwardPin, LOW);
  delay(pauseBetweenTestsMs);
}

// Ramps both motors together from 0 up to maxSpeed and back down to 0 in
// the same direction, so you can confirm the robot drives straight instead
// of pulling to one side, even if each motor tested fine on its own.
void sweepBothMotors(bool forward) {
  digitalWrite(leftForwardPin, forward ? HIGH : LOW);
  digitalWrite(leftBackwardPin, forward ? LOW : HIGH);
  digitalWrite(rightForwardPin, forward ? HIGH : LOW);
  digitalWrite(rightBackwardPin, forward ? LOW : HIGH);

  Serial.println(forward ? "Both motors: forward, ramping up" : "Both motors: backward, ramping up");
  for (int speed = 0; speed <= maxSpeed; speed += 5) {
    analogWrite(leftEnablePin, speed);
    analogWrite(rightEnablePin, speed);
    delay(stepDelayMs);
  }

  Serial.println("...ramping back down");
  for (int speed = maxSpeed; speed >= 0; speed -= 5) {
    analogWrite(leftEnablePin, speed);
    analogWrite(rightEnablePin, speed);
    delay(stepDelayMs);
  }

  digitalWrite(leftForwardPin, LOW);
  digitalWrite(leftBackwardPin, LOW);
  digitalWrite(rightForwardPin, LOW);
  digitalWrite(rightBackwardPin, LOW);
  delay(pauseBetweenTestsMs);
}

void loop() {
  sweepMotor("Left motor", leftEnablePin, leftForwardPin, leftBackwardPin, true);
  sweepMotor("Left motor", leftEnablePin, leftForwardPin, leftBackwardPin, false);
  sweepMotor("Right motor", rightEnablePin, rightForwardPin, rightBackwardPin, true);
  sweepMotor("Right motor", rightEnablePin, rightForwardPin, rightBackwardPin, false);
  sweepBothMotors(true);
  sweepBothMotors(false);

  Serial.println("Sweep complete. If a wheel spun the wrong way, swap that motor's two wires at the L298N and try again.");
  delay(pauseBetweenTestsMs * 3);
}
`,
};
