import { GeneralProject } from "@/lib/types";

export const ultrasonicBuzzer: GeneralProject = {
  id: "ultrasonic-buzzer",
  name: "Distance Buzzer (Ultrasonic Theremin)",
  description:
    "Uses an ultrasonic sensor to change the pitch of a buzzer based on distance - the closer your hand gets, the higher the pitch, like a tiny theremin.",
  wiringImage: "/images/wiring/ultrasonic-buzzer.svg",
  pins: [
    { label: "Ultrasonic VCC", arduinoPin: "5V" },
    { label: "Ultrasonic GND", arduinoPin: "GND" },
    { label: "Ultrasonic Trig", arduinoPin: "9" },
    { label: "Ultrasonic Echo", arduinoPin: "10" },
    { label: "Buzzer +", arduinoPin: "8" },
    { label: "Buzzer -", arduinoPin: "GND" },
  ],
  parameters: [
    {
      id: "minDistanceCm",
      label: "Closest Distance (Highest Pitch)",
      type: "number",
      defaultValue: 5,
      min: 2,
      max: 50,
      step: 1,
      unit: "cm",
    },
    {
      id: "maxDistanceCm",
      label: "Farthest Distance (Silence)",
      type: "number",
      defaultValue: 50,
      min: 10,
      max: 200,
      step: 5,
      unit: "cm",
    },
  ],
  explanation:
    "The ultrasonic sensor measures distance the same way it does for obstacle avoidance - it times how long a sound pulse takes to bounce back. Instead of stopping a motor, this code feeds that distance into map(), which scales it onto a pitch: close by plays a high tone, far away plays a low tone, and once something is farther than the silence distance the buzzer stops entirely. tone() is a built-in Arduino function that makes a pin buzz at a chosen frequency (in Hz) - no library needed.",
  code: `/*
  Distance Buzzer (Ultrasonic Theremin)
  Generated by the Robot Code Builder
*/

const int trigPin = 9;
const int echoPin = 10;
const int buzzerPin = 8;

const int minDistanceCm = {{minDistanceCm}}; // distance and closer -> highest pitch
const int maxDistanceCm = {{maxDistanceCm}}; // distance and farther -> silence

const int minToneHz = 200;  // lowest pitch, played near maxDistanceCm
const int maxToneHz = 2000; // highest pitch, played at minDistanceCm or closer

void setup() {
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  pinMode(buzzerPin, OUTPUT);
}

long readDistanceCm() {
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);

  long duration = pulseIn(echoPin, HIGH);
  return duration / 29 / 2;
}

void loop() {
  long distance = readDistanceCm();

  if (distance <= 0 || distance >= maxDistanceCm) {
    // Nothing in range (or the sensor didn't get a reading back) - stay quiet.
    noTone(buzzerPin);
    return;
  }

  // Clamp so anything closer than minDistanceCm still plays the highest pitch
  // instead of trying to go even higher.
  if (distance < minDistanceCm) {
    distance = minDistanceCm;
  }

  // map() scales distance (close-to-far) onto pitch (high-to-low): the closer
  // the object, the higher the tone.
  int pitch = map(distance, minDistanceCm, maxDistanceCm, maxToneHz, minToneHz);
  tone(buzzerPin, pitch);

  delay(50); // brief pause so the pitch doesn't flicker between readings
}
`,
};
